In [5]:
from openpyxl import load_workbook
import numpy as np
import pandas as pd
import requests

In [6]:
with open(f"retail-sales_total.xlsx", "wb") as f:
    x = (f'https://www.ons.gov.uk/file?'
         f'uri=%2fbusinessindustryandtrade'
         f'%2fretailindustry%2fdatasets'
         f'%2fpoundsdatatotalretailsales'
         f'%2fcurrent/poundsdata1.xlsx')
    f.write(requests.get(x).content)

with open(f"retail-sales_internet.xlsx", "wb") as f:
    y = (f'https://www.ons.gov.uk/file?'
         f'uri=%2fbusinessindustryandtrade'
         f'%2fretailindustry%2fdatasets'
         f'%2fretailsalesindexinternetsales'
         f'%2fcurrent/internetsalesreferencetables.xlsx')
    f.write(requests.get(x).content)

In [7]:
wb = load_workbook('retail-sales_internet.xlsx')
x = []

for row in wb.worksheets[9].iter_rows(min_row=7, max_col=None, max_row=None, values_only=True):
    x.append(row)
# flat_list = [item for sublist in x for item in sublist]

df = pd.DataFrame(x[4:],columns=x[0]).rename({None: 'Date'}, axis=1).set_index('Date').fillna(value=np.nan)
df = df.dropna(axis=0, how='all')
# df.where(df.notnull(), None)
df

,All retailing including automotive fuel,Month as a % of Total,All Retailing excluding automotive fuel,Month as a % of Total,Predominantly food stores,Total,Non-specialised stores,"Textile, clothing and footwear stores",Household goods stores,Other stores,Non-store retailing,Automotive fuel,Total Annual Sales for All Retailing including automotive fuel,Total Annual Sales for All Retailing excluding automotive fuel
Date,,,,,,,,,,,,,,
1994 Jan,NaN,NaN,13098758.0,NaN,5262001.0,6909100.0,1202474.0,1764226.0,1745610.0,2196790.0,927657.0,NaN,NaN,NaN
1994 Feb,NaN,NaN,12850749.0,NaN,5217322.0,6691698.0,1142494.0,1706435.0,1678974.0,2163795.0,941729.0,NaN,NaN,NaN
1994 Mar,NaN,NaN,16303609.0,NaN,6548609.0,8591931.0,1483473.0,2209544.0,2116585.0,2782329.0,1163069.0,NaN,NaN,NaN
1994 Apr,NaN,NaN,12972631.0,NaN,5250410.0,6776972.0,1164800.0,1753226.0,1700027.0,2158919.0,945249.0,NaN,NaN,NaN
1994 May,NaN,NaN,13114290.0,NaN,5266231.0,6888685.0,1170297.0,1760307.0,1708970.0,2249111.0,959374.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021 Jun,46263741.0,NaN,42087937.0,NaN,17453171.0,18029832.0,3271002.0,4497018.0,3990541.0,6271271.0,6604934.0,4175804.0,NaN,NaN
2021 Jul,36150742.0,NaN,32664159.0,NaN,13661875.0,13853795.0,2587848.0,3529697.0,3036424.0,4699826.0,5148489.0,3486583.0,NaN,NaN
2021 Aug,36087331.0,NaN,32559797.0,NaN,13543643.0,13914456.0,2529567.0,3611098.0,3012687.0,4761104.0,5101698.0,3527534.0,NaN,NaN
2021 Sep,45187994.0,NaN,40637557.0,NaN,17056577.0,17287676.0,3273458.0,4562657.0,3524069.0,5927492.0,6293304.0,4550437.0,NaN,NaN
2021 Oct,36716586.0,NaN,33184516.0,NaN,13663876.0,14497290.0,2649117.0,3875633.0,2874825.0,5097715.0,5023350.0,3532070.0,NaN,NaN

In [9]:
wb = load_workbook('retail-sales_total.xlsx')
x = []

for row in wb.worksheets[9].iter_rows(min_row=7, max_col=None, max_row=None, values_only=True):
    x.append(row)

df = pd.DataFrame(x[4:],columns=x[0]).rename({None: 'Date'}, axis=1).set_index('Date').fillna(value=np.nan)
df = df.dropna(axis=0, how='all')
df

,All retailing including automotive fuel,Month as a % of Total,All Retailing excluding automotive fuel,Month as a % of Total,Predominantly food stores,Total,Non-specialised stores,"Textile, clothing and footwear stores",Household goods stores,Other stores,Non-store retailing,Automotive fuel,Total Annual Sales for All Retailing including automotive fuel,Total Annual Sales for All Retailing excluding automotive fuel
Date,,,,,,,,,,,,,,
1994 Jan,NaN,NaN,13098758.0,NaN,5262001.0,6909100.0,1202474.0,1764226.0,1745610.0,2196790.0,927657.0,NaN,NaN,NaN
1994 Feb,NaN,NaN,12850749.0,NaN,5217322.0,6691698.0,1142494.0,1706435.0,1678974.0,2163795.0,941729.0,NaN,NaN,NaN
1994 Mar,NaN,NaN,16303609.0,NaN,6548609.0,8591931.0,1483473.0,2209544.0,2116585.0,2782329.0,1163069.0,NaN,NaN,NaN
1994 Apr,NaN,NaN,12972631.0,NaN,5250410.0,6776972.0,1164800.0,1753226.0,1700027.0,2158919.0,945249.0,NaN,NaN,NaN
1994 May,NaN,NaN,13114290.0,NaN,5266231.0,6888685.0,1170297.0,1760307.0,1708970.0,2249111.0,959374.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021 Jun,46263741.0,NaN,42087937.0,NaN,17453171.0,18029832.0,3271002.0,4497018.0,3990541.0,6271271.0,6604934.0,4175804.0,NaN,NaN
2021 Jul,36150742.0,NaN,32664159.0,NaN,13661875.0,13853795.0,2587848.0,3529697.0,3036424.0,4699826.0,5148489.0,3486583.0,NaN,NaN
2021 Aug,36087331.0,NaN,32559797.0,NaN,13543643.0,13914456.0,2529567.0,3611098.0,3012687.0,4761104.0,5101698.0,3527534.0,NaN,NaN
2021 Sep,45187994.0,NaN,40637557.0,NaN,17056577.0,17287676.0,3273458.0,4562657.0,3524069.0,5927492.0,6293304.0,4550437.0,NaN,NaN
2021 Oct,36716586.0,NaN,33184516.0,NaN,13663876.0,14497290.0,2649117.0,3875633.0,2874825.0,5097715.0,5023350.0,3532070.0,NaN,NaN